services:
    app:
        build:
            context: .
            dockerfile: build/Dockerfile
        container_name: codeigniter_app
        ports:
            - "8111:80"
        volumes:
            - ./:/var/www/html
        environment:
            - CI_ENVIRONMENT=development
        depends_on:
            - db

    db:
        image: mysql:8.3
        container_name: codeigniter_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: your_root_password
            MYSQL_DATABASE: your_database_name
            MYSQL_USER: your_username
            MYSQL_PASSWORD: your_password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin:5.2-apache
        container_name: codeigniter_phpmyadmin
        ports:
            - "8001:80"
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=your_username
            - PMA_PASSWORD=your_password
        depends_on:
            - db

volumes:
    db_data: